In [1]:
import numpy as np

1. 정수 1로 채워진 3x3 배열 생성

In [4]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

2. 0부터 10까지 채워진 배열 생성하고 5번째 숫자를  0으로 변환

In [11]:
a = np.arange(1,11)
print(a)
a[4] = 0
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  0  6  7  8  9 10]


3. 0부터 8까지 채워진 배열을 생성한 뒤 3x3 형태로 변환

In [13]:
b = np.arange(0, 9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. 다음 배열에서 0이 아닌 벡터들의 위치를 출력

5. 모든 값이 랜덤한 값을 가지는 3x3x3 형태의 배열 생성

In [33]:
np.random.random((3, 3))

array([[0.2637233 , 0.07715954, 0.04582726],
       [0.89454871, 0.08832289, 0.7165683 ],
       [0.0356426 , 0.63460635, 0.94581595]])

6. min, max, mean값을 출력

In [18]:
test_array = np.array([[1,2,5,3,4],[10,15,13,46,8],[10,2,4,8,9],[7,85,5,2,44],[4,5,68,7,92]])

In [21]:
a = np.min(test_array)
b = np.max(test_array)
c = np.mean(test_array)
print(a)
print(b)
print(c)

1
92
18.36


7. 정수 1로 채워진 10x10 형태의 배열을 생성하고 테두리는 1, 내부는 0인 상태로 변환

In [35]:
a = np.ones((10, 10))
a[1:9, 1:9] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


8. 정수 0으로 채워진 10x10 형태의 배열을 생성하고 체스판 형태의 상태로 변환 (0,1,0,1,0,1,0,1)

In [ ]:
b = np.zeros((10, 10))
c = ['False','True','False','True','False','True','False','True','False','True']


9. 배열 합치기 (더하기가 아님)

In [32]:
arr9_1 = np.array([1,2,3])
arr9_2 = np.array([4,5,6])

10. 0부터 9로 채워진 배열을 5를 기준으로 나눌 것

In [40]:
a = np.arange(0, 10)
print(a)
b, c = np.split(a, [5])
print(b,c)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


11. 0부터 9으로 채워진 배열을 짝수를 기준으로 나눌 것

In [44]:
a = np.arange(0, 10)
print(a)
b, c, d, e, f = np.split(a, [2, 4, 6, 8])
print(b, c, d, e, f)

[0 1 2 3 4 5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


12. arr12 = np.random.randint(-10, 10, size=5)일 때, 절대값 및 제곱/제곱근을 출력

In [50]:
arr12 = np.random.randint(-10, 10, size=5)
print(arr12)
# 절댓값
print(np.abs(arr12))
# 제곱
print(np.square(arr12))
# 제곱근
print(np.sqrt(arr12))

[-3  3  5 -9  2]
[3 3 5 9 2]
[ 9  9 25 81  4]
[       nan 1.73205081 2.23606798        nan 1.41421356]


<ipython-input-50-6f8dee11f9a8>:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr12))


13. arr13 = np.random.randint(1, 10, size=5)일 때, 지수와 로그함수를 출력

In [53]:
arr13 = np.random.randint(1, 10, size=5)
print(arr13)
# 지수
print(np.exp(arr13))
# 로그
print(np.log(arr13))

[2 2 2 4 6]
[  7.3890561    7.3890561    7.3890561   54.59815003 403.42879349]
[0.69314718 0.69314718 0.69314718 1.38629436 1.79175947]


14. 배열 형태 바꾸기
arr14 = np.array([1,2,3,4])를 2x2형태로 변환

In [55]:
arr14 = np.array([1,2,3,4])
print(arr14)
arr14.reshape(2, 2)

[1 2 3 4]


array([[1, 2],
       [3, 4]])

15. arr15 = np.arange(1, 15)일 때, 8보다 작은 값들을 boolean리스트로 생성하고 해당 값들을0으로 변환  >>> 마스킹 사용

In [57]:
arr15 = np.arange(1, 15)
print(arr15)
print(arr15 < 8)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ True  True  True  True  True  True  True False False False False False
 False False]


16. 2x5 형태의 배열을 생성하고 각 행과 열의 합을 출력  >>> 집계함수는 특정한 축을 기준으로 출력 가능

In [60]:
a = np.random.randint(1, 10, size=(2, 5))
print(a)
# 열의 합
print(np.sum(a, axis = 0))
# 행의 합
print(np.sum(a, axis = 1))

[[2 7 5 6 9]
 [8 4 4 8 4]]
[10 11  9 14 13]
[29 28]


17. 0부터 9까지 정수 중 5개를 랜덤하게 선택하는 배열 생성  (단, 짝수가 뽑히는 확률은 0으로 설정)

18. 다음 두개의 배열에서 공통된 인자를 구하라

In [ ]:
arr18_1 = np.random.randint(0,10,10)
arr18_2 = np.random.randint(0,10,10)