In [49]:
from konlpy.utils import pprint
from konlpy.tag import Kkma

kkma = Kkma()
pprint(kkma.sentences(u'도움'))

['도움']


In [26]:
# 데이터 크롤링 ppt 137p
word_list = [
    '남자 남자 남자 밥밥',
    '남자 남자',
    '남자 남자 남자',
    '남자 남자 남자 여자 여자',
    '남자 남자 남자 밥밥 밥밥'
]

In [2]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [27]:
## TF-IDF벡터값을 구하는 라이브러리(TfidfVectorizer)
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tf_idf = TfidfVectorizer()

In [29]:
tf_idf.fit_transform(word_list)

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [30]:
## 문장의 벡터화가 진행된다.
vector = tf_idf.fit_transform(word_list)

In [31]:
vector.A

array([[0.87087416, 0.49150604, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.58149261, 0.        , 0.81355169],
       [0.66312327, 0.7485102 , 0.        ]])

In [41]:
# min_df는 지정한 값보다 작은 경우에 무시한다.
tf_idf = TfidfVectorizer(min_df = 1)
vector = tf_idf.fit_transform(word_list)
vector.A

array([[0.87087416, 0.49150604, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.58149261, 0.        , 0.81355169],
       [0.66312327, 0.7485102 , 0.        ]])

In [42]:
## 인덱스를 확인
tf_idf.get_feature_names()

['남자', '밥밥', '여자']

In [34]:
## text에서 명사만 리턴할 것임
# 명사는 주제를 파악할 때, 사용
# 형용사는 감정 분석할 때 사용
def getNoun(text):
    print('text = ', text)
    stems = text.split(' ')
    print('stems = ', stems)
    print('=' * 30)
    return stems

In [35]:
# tokenizer은 문장을 일정한 규칙으로 나누는 과정
tf_idf = TfidfVectorizer(tokenizer=getNoun, smooth_idf=False)

In [36]:
# text에 word_list 문장이 한 개씩 들어간다.
tf_idf.fit_transform(word_list)
# 모든 단어가 다 리턴이 되었고 모든 tf_idf의 값이 계산되었다.

text =  남자 남자 남자 밥밥
stems =  ['남자', '남자', '남자', '밥밥']
text =  남자 남자
stems =  ['남자', '남자']
text =  남자 남자 남자
stems =  ['남자', '남자', '남자']
text =  남자 남자 남자 여자 여자
stems =  ['남자', '남자', '남자', '여자', '여자']
text =  남자 남자 남자 밥밥 밥밥
stems =  ['남자', '남자', '남자', '밥밥', '밥밥']


<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [37]:
vector = tf_idf.fit_transform(word_list)

text =  남자 남자 남자 밥밥
stems =  ['남자', '남자', '남자', '밥밥']
text =  남자 남자
stems =  ['남자', '남자']
text =  남자 남자 남자
stems =  ['남자', '남자', '남자']
text =  남자 남자 남자 여자 여자
stems =  ['남자', '남자', '남자', '여자', '여자']
text =  남자 남자 남자 밥밥 밥밥
stems =  ['남자', '남자', '남자', '밥밥', '밥밥']


In [38]:
vector

<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [39]:
## 결과를 보기
vector.A

array([[0.84274417, 0.53831428, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.49836455, 0.        , 0.86696757],
       [0.61638324, 0.78744632, 0.        ]])

In [40]:
tf_idf.get_feature_names()

['남자', '밥밥', '여자']