In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [1]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [3]:
from tensorflow import keras
from tensorflow.keras import layers


In [4]:
from keras.layers import Dense, Activation

model = keras.Sequential()

model.add(Dense(input_dim=2, units=1))
model.add(Activation('sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [5]:
# sgb 사용
# sgb = keras.optimizers.SGD(lr=1)
# model.compile(loss='binary_crossentropy', optimizer=sgd)

# adam 사용
adam = keras.optimizers.Adam(lr=1)
model.compile(loss='binary_crossentropy', optimizer=adam)

In [6]:
model.fit(X, y, batch_size=1, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 1.1550
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3164
Epoch 3/100
4/4 [==============================] - 0s 916us/step - loss: 0.6411
Epoch 4/100
4/4 [==============================] - 0s 812us/step - loss: 0.1683
Epoch 5/100
4/4 [==============================] - 0s 815us/step - loss: 0.6759
Epoch 6/100
4/4 [==============================] - 0s 786us/step - loss: 0.1235
Epoch 7/100
4/4 [==============================] - 0s 782us/step - loss: 0.0158
Epoch 8/100
4/4 [==============================] - 0s 752us/step - loss: 0.0494
Epoch 9/100
4/4 [==============================] - 0s 870us/step - loss: 0.0331
Epoch 10/100
4/4 [==============================] - 0s 850us/step - loss: 0.0231
Epoch 11/100
4/4 [==============================] - 0s 835us/step - loss: 0.0268
Epoch 12/100
4/4 [==============================] - 0s 1ms/step - loss: 0.0229
Epoch 13/100
4/4 [=========================

In [7]:
test_data = np.array([[0,0], [0,1], [1,1]])

print(model.predict(test_data))
print(model.predict_classes(test_data))

[[0.00359118]
 [0.9988926 ]
 [1.        ]]
[[0]
 [1]
 [1]]


/anaconda/envs/py38_tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '
