### 딥-러닝 과정 Mulit Layer Perceptron(MLP) 

## Simple Keras 모델 생성/학습 - XOR Function

In [1]:
# 1. Numpy 가져오기

import numpy as np

In [2]:
# 2. 입력/출력 데이터 만들기

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
# 3. Keras 패키지 가져오기

from tensorflow import keras
from tensorflow.keras import layers
from keras.layers import Dense, Activation

In [21]:
# 4. MLP 모델 생성

model =  keras.Sequential()
# input은 2개니깐 2개 적어주기. units의 노드 개수를 확 늘려주면 안정적이게 된다.
model.add(Dense(input_dim=2, units=8))
model.add(Activation('relu'))
# 만약에 층을 여러개쌓는다면 최대한 단순하게 하는 것이 좋다. units는 낮을수록 좋긴한데 결과가 안나오면 올리는데 2의 배수로 올리는게 좋다.
model.add(Dense(units=1))
model.add(Activation('sigmoid'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 8)                 24        
_________________________________________________________________
activation_8 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 9         
_________________________________________________________________
activation_9 (Activation)    (None, 1)                 0         
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [22]:
# 5. Compile - Optimizer, Loss function 설정
# sgd = keras.optimizers.SGD(lr=0.1)
# model.compile(loss='binary_crossentropy', optimizer=sgd)
adam = keras.optimizers.Adam(lr=0.07)
model.compile(loss='binary_crossentropy', optimizer=adam)

In [23]:
# 6. 학습시키기
model.fit(X, y, batch_size=1, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 0.7589
Epoch 2/100
4/4 [==============================] - 0s 825us/step - loss: 0.6785
Epoch 3/100
4/4 [==============================] - 0s 871us/step - loss: 0.6503
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 0.5991
Epoch 5/100
4/4 [==============================] - 0s 864us/step - loss: 0.5755
Epoch 6/100
4/4 [==============================] - 0s 932us/step - loss: 0.5114
Epoch 7/100
4/4 [==============================] - 0s 966us/step - loss: 0.4877
Epoch 8/100
4/4 [==============================] - 0s 864us/step - loss: 0.4782
Epoch 9/100
4/4 [==============================] - 0s 817us/step - loss: 0.4173
Epoch 10/100
4/4 [==============================] - 0s 947us/step - loss: 0.4417
Epoch 11/100
4/4 [==============================] - 0s 879us/step - loss: 0.2975
Epoch 12/100
4/4 [==============================] - 0s 952us/step - loss: 0.3434
Epoch 13/100
4/4 [=======================

In [24]:
# 7. 모델 테스트하기 
test_data = np.array([[0,0], [1,0], [1,1]]) # [0, 1, 0]

print(model.predict(test_data))
print(model.predict_classes(test_data))

[[2.6352704e-03]
 [9.9892867e-01]
 [9.4211102e-04]]
[[0]
 [1]
 [0]]
