## 데이터 사이언스 스쿨

### 3장 넘파이 배열 프로그래밍

### 3.1 넘파이 배열

In [3]:
# 연습문제 3.1.1

import numpy as np

c = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [11]:
# 연습문제 3.1.2

m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

m[1,2]
m[-1, -1]
m[1, 1:3]
m[1:,2]
m[:2, 3:]


array([[3, 4],
       [8, 9]])

In [17]:
# 연습문제 3.1.3

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

x[x % 3 == 0]
x[x % 4 == 1]
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

### 3.2 배열의 생성과 변형

In [31]:
# 연습문제 3.2.1

a1 = np.zeros((3,3))
a2 = np.ones((3, 2))
hstack = np.hstack([a1,a2])
a3 = np.arange(10, 60, 10)
a4 = np.arange(60, 110, 10)
a5 = np.arange(110, 160, 10)
vstack = np.vstack([a3,a4,a5])
first_line = np.vstack([hstack, vstack])
total = np.vstack([first_line, first_line])
print(total)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


### 3.3 배열의 연산